Link librt to fix build with old glibc
Building on CentOS 6 yielded:

  nnn.c:(.text+0x5430): undefined reference to `clock_gettime'

Older glibc versions require librt to be linked for clock_*.

Fixes #453